global:
    tags:
        project: APO
        algorithm: prophet
    role_arn: arn:aws:iam::150258775384:role/FORECAST-SAGEMAKER-DEV
    security_group_ids: sg-0186b5ab868f43e42
    subnets: subnet-0f87a7ed73f4ead6d, subnet-02c60aed04f0d4ee5
    
train:
    bucket_input: fcst-workspace
    bucket_output: fcst-workspace
    path_refined_data_input: qlik/data/refined/domyos_nov_2019/cutoff_data
    path_refined_data_output: qlik/data/refined/domyos_nov_2019/gluonts_data
    docker_image: 150258775384.dkr.ecr.eu-west-1.amazonaws.com/apo-demand-forecast-training:latest
    job_name: demand-forecast-prophet
    instance_type: ml.m4.xlarge
    instance_count: 1
    hyperparameters:
        yearly_order': 25
        quaterly_order': 5
        weekly_seasonality: False
        daily_seasonality: False
        yearly_seasonality: False
        n_changepoints: 36
        changepoint_range: 0.69
        changepoint_prior_scale: 1.91
        seasonality_prior_scale: 2.04
        