global:
    tags:
        Key: project
        Value: apo
    algorithm: prophet
    environment: dev
    role_arn: arn:aws:iam::150258775384:role/FORECAST-SAGEMAKER-DEV
    security_group_ids: sg-0186b5ab868f43e42
    subnets: subnet-0f87a7ed73f4ead6d, subnet-02c60aed04f0d4ee5
    volume_size_in_gb: 10
    
train:
    bucket_input: fcst-refined-demand-forecast-dev
    bucket_output: fcst-refined-demand-forecast-dev
    path_refined_data_input: specific/domyos_nov_2019/train_data_cutoff/
    path_refined_data_intermediate: specific/domyos_nov_2019/train_data_cutoff_gluonts/
    path_refined_data_output: model/results/domyos_nov_2019/
    image_name: demand-forecast-prophet-training
    docker_image: 150258775384.dkr.ecr.eu-west-1.amazonaws.com/demand-forecast-prophet-training:latest
    job_name: demand-forecast-prophet-training
    instance_type: ml.m5.2xlarge
    instance_count: 1
    hyperparameters:
        yearly_order: 25
        quaterly_order': 5
        weekly_seasonality: False
        daily_seasonality: False
        yearly_seasonality: False
        n_changepoints: 36
        changepoint_range: 0.69
        changepoint_prior_scale: 1.91
        seasonality_prior_scale: 2.04
        