global:
    tags:
        project: apo
        algorithm: prophet
        environment: dev
    role_arn: arn:aws:iam::150258775384:role/FORECAST-SAGEMAKER-DEV
    security_group_ids: sg-0186b5ab868f43e42
    subnets: subnet-0f87a7ed73f4ead6d, subnet-02c60aed04f0d4ee5
    volume_size_in_gb: 10
    
train:
    bucket_input: fcst-refined-demand-forecast-dev
    bucket_output: fcst-refined-demand-forecast-dev
    image_name: demand-forecast-prophet-training
    instance_type: ml.c5.2xlarge
    instance_count: 1
    max_run_time: 86400 # seconds
    hyperparameters:
        yearly_order: 27
        quaterly_order': 5
        weekly_seasonality: False
        daily_seasonality: False
        yearly_seasonality: False
        n_changepoints: 36
        changepoint_range: 0.6970858418088761
        changepoint_prior_scale: 1.9131406810094054
        seasonality_prior_scale: 2.0461437728104253

monitor:
    sleep: 300 # seconds
        