FROM 150258775384.dkr.ecr.eu-west-1.amazonaws.com/mxnet-gluonts-training-0.3.3-cpu:latest

COPY ../src/ /opt/program
COPY ../config/ /opt/program

ENV RUN_ENV ${RUN_ENV}
ENV ONLY_LAST ${ONLY_LAST}
ENV SM_CHANNEL_TRAIN /opt/ml/input/data/training
ENV SM_MODEL_DIR /opt/ml/model

ENTRYPOINT ["python"]