buckets:
  refined_data_global: fcst-refined-demand-forecast-prod
  refined_data_specific: fcst-refined-demand-forecast-prod
paths:
  refined_global_path: global/
  refined_specific_path: specific/
refining_specific_parameters:
  rec_cold_start: true
  rec_cold_start_length: 104
  rec_cold_start_group:
  - family_id
modeling_parameters:
  hyperparameters:
    time_freq : W
    prediction_length: 52
    context_length: 52
    epochs : 50
    likelihood : student-T
    early_stopping_patience: 5
    learning_rate: 1e-3
    mini_batch_size: 512
    num_layers: 2
    num_cells: 40 #100
    dropout_rate: 0.1
    cardinality: auto
    embedding_dimension: 10 #50
    num_dynamic_feat: auto
    num_eval_samples: 100
    test_quantiles:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
  algorithm: deepAR
  image_name_label: forecasting-deepar
  train_max_instances: 10
  transform_max_instances: 5
  role: arn:aws:iam::150258775384:role/FORECAST-SAGEMAKER-DEV
  tags:
    Key: project
    Value: demand-forecast
  train_instance_type: ml.p3.2xlarge
  train_max_run: 3600
  train_max_wait: 3600
  train_use_spot_instances: false
  train_instance_count: 1
  transform_instance_type: ml.c5.18xlarge
  transform_instance_count: 1

