buckets:
  refined_data_global: fcst-refined-demand-forecast-prod
  refined_data_specific: fcst-refined-demand-forecast-prod
paths:
  refined_global_path: global/
  refined_specific_path: specific/
refining_specific_parameters:
  patch_first_lockdown: True
  rec_length: 156
  rec_cold_start: true 
  rec_cold_start_group:
  - family_id
modeling_parameters:
  role: arn:aws:iam::150258775384:role/FORECAST-SAGEMAKER-PROD
  tags:
    Key: project
    Value: demand-forecast
  train_use_spot_instances: False
  deepar_arima_stacking: True
  algorithm:
    deepar:
      image_name: 224300973850.dkr.ecr.eu-west-1.amazonaws.com/forecasting-deepar:1
      hyperparameters:
        time_freq: W
        prediction_length: 16
        context_length: 52
        epochs: 100
        likelihood: student-T
        early_stopping_patience: 100
        learning_rate: 1e-3
        mini_batch_size: 512
        num_layers: 2
        num_cells: 40
        dropout_rate: 0.1
        cardinality: auto
        embedding_dimension: 20
        num_dynamic_feat: auto
        num_eval_samples: 100
        test_quantiles:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
      train_instance_count: 1
      train_instance_type: ml.p3.2xlarge
      train_max_instances: 20
      transform_instance_count: 1
      transform_instance_type: ml.c5.9xlarge
      transform_max_instances: 20
      max_concurrent_transforms: 36
    arima:
      image_name: 150258775384.dkr.ecr.eu-west-1.amazonaws.com/pmdarima_sagemaker:latest
      hyperparameters:
        prediction_length: 104
        context_length: 156
        fourier_seasonal_period: 52
        fourier_order: 10
        arima_differencing_order: 1
        arima_criterion: aicc
        arima_optimizer: nm
      train_instance_count: 1
      train_instance_type: ml.c5.18xlarge
      train_max_instances: 20